package com.viam.feeder.constants

const val EVENT_FEEDING = "EVENT_FEEDING"
const val EVENT_LED_TIMER = "EVENT_LED_TIMER"
const val EVENT_PLAY_FEEDING_AUDIO = "EVENT_PLAY_FEEDING_AUDIO"
const val EVENT_COMPOSITE_FEEDING = "EVENT_COMPOSITE_FEEDING"
