package com.viam.feeder.constants

import androidx.annotation.StringDef


const val SETTING_FEEDING_INTERVAL = "SETTING_FEEDING_INTERVAL"
const val SETTING_SOUND_VOLUME = "SETTING_SOUND_VOLUME"
const val SETTING_FEED_DURATION = "SETTING_FEED_DURATION"
const val SETTING_LED_TURN_OFF_DELAY = "SETTING_LED_TURN_OFF_DELAY"
const val SETTING_LED_STATE = "SETTING_LED_STATE"
const val SETTING_WIFI_PASS = "SETTING_WIFI_SETTINGS"
const val SETTING_FEEDING_ALARM = "SETTING_FEEDING_ALARM"

@Retention(AnnotationRetention.SOURCE)
@StringDef(
    SETTING_FEEDING_INTERVAL,
    SETTING_SOUND_VOLUME,
    SETTING_FEED_DURATION,
    SETTING_LED_TURN_OFF_DELAY,
    SETTING_LED_STATE,
    SETTING_WIFI_PASS,
)
annotation class Settings